// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-t-isz-V3LA-nWhlA9VXZoXMZSa3X_I',
    appId: '1:970504896474:android:be54ddd3eada30bc130ae3',
    messagingSenderId: '970504896474',
    projectId: 'we-chat-2b500',
    storageBucket: 'we-chat-2b500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2c33F0UN1rdfKq_BcJlyJKLXYLZ5c6EA',
    appId: '1:970504896474:ios:a84e6755381e0aef130ae3',
    messagingSenderId: '970504896474',
    projectId: 'we-chat-2b500',
    storageBucket: 'we-chat-2b500.appspot.com',
    androidClientId: '970504896474-epao5q0d647vbgghrl92v4vol5ammk9c.apps.googleusercontent.com',
    iosClientId: '970504896474-40hprfmtf3lu60t6rgmjhvpgsqddplnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
